export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const SET_CURRENT_GAME = "SET_CURRENT_GAME";

export const AuthActionType = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const Alerts = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
};

export const ProfileActionType = {
  PROFILE_LOAD_SUCCESS: "PROFILE_LOAD_SUCCESS",
  PROFILE_LOAD_FAIL: "PROFILE_LOAD_SUCCESS",
  PROFILE_REQUEST: "PROFILE_REQUEST",
};
